version: "2"

services:
  database:
    image: bornabesic/pgdb-database:0.1
    container_name: pgdb-database
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - pgdb-network
  web:
    image: bornabesic/pgdb-web:0.1
    container_name: pgdb-web
    ports:
      - 5000:5000
    networks:
      - pgdb-network

networks:
  pgdb-network: {}
