name: pgdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - py2neo #==4.3 current py2neo library is 2020.0.0
  - psycopg2
  - pyyaml
  - pylint
  - flask
  - networkx>=2.2
  - numpy
  - scipy #
  - pandas
  - packaging
  - neomodel
  - monotonic
  - neo4j-python-driver # - neo4j-driver==1.6.2 #exact version needed to remain compatible with py2neo v4.0