version: 2
jobs:
  build:
    working_directory: ~/protein-graph-database
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: string
      - image: neo4j:3.4.8
        environment:
          NEO4J_AUTH: none
    branches:
      only:
        - master
    steps:
    - checkout
    - run:
        name: Set up the conda environment
        command: |
          sudo apt update
          sudo apt install -y postgresql-client
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          make env
    - run:
        name: Set the environment variables
        command: |
          echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> $BASH_ENV
    - run:
        name: Wait for PostgreSQL to start
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 2
          done
          echo Failed waiting for Postgres && exit 1
    - run:
        name: Run tests
        command: |
          ln -s tests/credentials.test.yml credentials.yml
          source activate pgdb
          make test

