name: test

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      # prepare environment
      - name: setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment.yml
          activate-environment: pgdb
      - name: black
        run: black --version
      # run tests
      - name: build application
        run: make build
      - name: test application
        run: make test
